Metrics Module
achains/plane-seg pull request #2
Opened 2022-07-20 08:06 UTC by true-real-michael

Added `run_metrics` and `rgb2labels` converters

2022-07-20 10:15 UTC, DmiitriyJarosh requested changes

2022-07-20 10:15 UTC, DmiitriyJarosh commented on python/plane_seg/metrics/get_metric.py
> +def get_metric(gtdata: Union[Image.Image, NDArray[Any, np.int32]],
откуда  image? мы не используем pil в проекте, пользуемся cv2

2022-07-20 10:15 UTC, DmiitriyJarosh commented on python/plane_seg/metrics/get_metric.py
> +def get_metric(gtdata: Union[Image.Image, NDArray[Any, np.int32]],
подгрузка gt данных пропущена также

2022-07-20 10:15 UTC, DmiitriyJarosh commented on python/plane_seg/metrics/get_metric.py
> +def get_metric(gtdata: Union[Image.Image, NDArray[Any, np.int32]],
нэйминг не норм - calculate_metrics или evaluate_metrics

2022-07-20 10:15 UTC, DmiitriyJarosh commented on python/plane_seg/metrics/get_metric.py
> +               preddata: Union[Image.Image, NDArray[Any, np.int32]],
слова не сокращаем, разделяем нижним подчеркиванием

2022-07-20 10:15 UTC, DmiitriyJarosh commented on python/plane_seg/metrics/rgb2labels.py
> +    labeled = reshaped[0] * 256**2 + reshaped[1] * 256 + reshaped[2]
красиво

2022-07-20 10:22 UTC, DmiitriyJarosh requested changes

2022-07-20 10:22 UTC, DmiitriyJarosh commented on python/plane_seg/metrics/get_metric.py
> +               metric: Callable[[NDArray[Any, np.int32], NDArray[Any, np.int32]], np.float64]) -> np.float64:
что здесь ожидается, нужна дока к методу

2022-07-20 13:51 UTC, DmiitriyJarosh requested changes

2022-07-20 13:51 UTC, DmiitriyJarosh commented on python/plane_seg/metrics/__main__.py
> +def main(argv):
не в этот же main) а в основной, зачем нам столько мэйнов

2022-07-20 13:51 UTC, DmiitriyJarosh commented on python/plane_seg/metrics/evaluate_metrics.py
> +        print(metric_value)
а как узнать что за метрика, там ведь одно число будет, не информативно

2022-07-20 21:30 UTC, achains commented on python/plane_seg/metrics/evaluate_metrics.py
> +    assert metric_name in ('iou', 'dice', 'precision-iou', 'recall-iou', 'fScore-iou', 'mean-iou', 'mean-dice'), \
С assert'ами для валидации входных параметров нужно быть очень осторожным

Если запускать Python с "релизными" флагами, то assert'ы становятся неактивными
Здесь лучше всего бросать исключения через `if ... raise ...`

2022-07-20 21:30 UTC, achains commented on python/plane_seg/metrics/__main__.py
> +def main(argv):
@DmiitriyJarosh, А насколько мы хотим совмещать запуск алгоритмов и результат метрик в одном main? 

Для основного инструмента я бы оставил только возможность запускать сами алгоритмы на данных. В этом же и есть суть обёртки.

2022-07-20 21:30 UTC, achains commented on python/plane_seg/metrics/evaluate_metrics.py
> +from evops.metrics import *
Давайте разделять from'ы и import'ы, так гораздо удобнее читать

Предлагаю придерживаться стиля "сначала все from, потом все import", как в остальном коде проекта

2022-07-21 11:23 UTC, achains requested changes
Сделайте пулл изменений из ветки tool-structure. 
Далее:
1. Добавьте в основной \_\_main\_\_ скрипт аргумент для вызова статистики по метрикам
2. Папка examples уже существует и лежит в python/, перенесите ваш пример с тестовыми данными туда

2022-07-21 16:22 UTC, achains requested changes
В целом хорошо, но давайте избавимся от дублирования кода. Пример в `examples` предлагаю оставить какой-нибудь один

2022-07-21 16:22 UTC, achains commented on python/plane_seg/metrics/metrics_evaluation.py
> +        with open(output_file, "a") as fout:
А если output_file будет непустой изначально? Точно ли флаг 'a' тут нужен?

2022-07-21 16:22 UTC, achains commented on python/plane_seg/metrics/metrics_evaluation.py
> +    all_metrics_values = {
Идею со словарём можно переиспользовать и в функции выше. Отличия в функциях минимальные, можно как-то избежать дублирования кода?

2022-07-21 16:22 UTC, achains commented on python/examples/evaluate_one_metric.py
> +if __name__ == "__main__":
Я думаю одного примера, пускай all_metrics, будет более чем достаточно. Содержательно они почти не отличаются.

2022-07-21 16:22 UTC, achains commented on python/examples/evaluate_all_metrics.py
> +    predicted_labels = np.load("data/metrics_example_perdictions.npy")
**perdictions** :)

2022-07-22 05:08 UTC, true-real-michael commented on python/plane_seg/metrics/metrics_evaluation.py
> +        with open(output_file, "a") as fout:
Специально так сделал, чтобы можно было в один файл несколько экспериментов записывать. Например, одно облако, но с разными параметрами.
Лучше поменять на 'w'?

2022-07-22 08:46 UTC, achains requested changes

2022-07-22 08:46 UTC, achains commented on python/plane_seg/metrics/metrics_evaluation.py
> +        with open(output_file, "a") as fout:
Давай будет 'w'. Я не хочу думать о том, пустой ли файл или нет. Один запуск алгоритма -- один артефакт. Всегда можно разные запуски раскидать по разным файлам, так их даже будет удобнее искать.

2022-07-22 08:46 UTC, achains commented on python/plane_seg/__main__.py
>              args.eval_metric,
А здесь предполагается что пользователь будет задавать одну метрику? Интерфейс соответствующей функции кажется принимает `Collection[AnyStr]`

2022-07-22 08:46 UTC, achains commented on python/plane_seg/__main__.py
>              args.eval_metric,
А если пользователь введёт название метрики с опечаткой? Кажется на это вообще нет никаких проверок

2022-07-22 08:46 UTC, achains commented on python/plane_seg/__main__.py
>              args.eval_metric,
Если несколько, то тип передаваемого аргумента это просто строка? А не будет потом проблем с проверками в духе `if "iou" in metric_names`, где metric_names это внезапно просто строка `"(recall-iou, dice)"`

2022-07-22 11:09 UTC, merged